backend:
  name: github
  repo: bdougie/huo-restaurant-tutorial
  branch: master

media_folder: "src/img/galley"

collections:
      name: food
      label: "Food item"
      folder: "site/content/food"
      create: true
      fields:
        -  {label: "Name of Item", name: "title", widget: "string"}
        -  {label: "Supported Meals", name: "cetegories", widget: "list", default: ["lunch","dinner"]}
        -  {label: "Ingredients/Description", name: "description", widget: "text"}
        -  {label: "Type of Food", name: "type", widget: "string"}
        -  {label: "Price", name: "price", widget: "string"}